### ISSUE TITLE
谷歌云安装DEBAN8无法进入系统,提示：我们无法通过端口 22 连接到 VM

### ISSUE THREAD

**Issue by embeddedsecurity** [0oVicero0/Debian-ReInstall#2]
具体原因请查看我上传的WORD文档，里面有详细的图文描述。好人一生平安，事事顺利！

**Comment by 0oVicero0** [comment]
需要自己指定  内网的  IP，网关，子网掩码。
无论是dd windows还是 安装linux，都能成功。

**Comment by embeddedsecurity** [comment]
delete

**Comment by 0oVicero0** [comment]
255.255.255.255 --> 255.255.255.0

**Comment by yun2673436976** [comment]
> 255.255.255.255 --> 255.255.255.0

感谢萌咖大佬，按照你的方法在谷歌云上重装ubuntu16成功。但我不明白，我在谷歌云里debian9里输入ifconfig，查到的子网掩码是255.255.255.255，填写255.255.255.255就不成功，难道是ifconfig查询VPS网络参数方法不准？
微软云也是内网，在微软云上输入ifconfig，查到的子网掩码就是255.255.255.0，重装系统时按照ifconfig给出的网络参数手动指定网络参数就OK。
